service: sc0

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ${env:AWS_REGION}

  environment:
    STRIPE_PUB: ${env:STRIPE_PUB}
    STRIPE_SECRET: ${env:STRIPE_SECRET}
    REGION: ${env:AWS_REGION}
    SES_SENDER: ${env:SES_SENDER}

package:
  include:
    - node_modules/**
  exclude:
    - /*/\.txt
    - /*/\.md
    - package.json
    - temp

functions:
  payouts:
    handler: payouts.payoutsHandler
    events:
      - http:
          path: payouts
          method: get
  balance:
    handler: balance.balanceHandler
    events:
      - http:
          path: balance
          method: get
  sendemail:
    handler: sendemail.sendemailHandler
    memorySize: 1024
    events:
      - http:
          path: sendemail
          method: post
          integration: lambda
