service: sc0

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

  environment:
    STRIPE_PUB: ${env:STRIPE_PUB}
    STRIPE_SECRET: ${env:STRIPE_SECRET}


package:
  include:
    - node_modules/**
  exclude:
    - package.json

functions:
  payouts:
    handler: payouts.payoutsHandler
  balance:
    handler: balance.balanceHandler
